name: Check PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  security-checks:
    name: Security tests
    if: |
      !github.event.pull_request.head.repo.fork && github.event.pull_request.user.login != 'dependabot[bot]'
    uses: ./.github/workflows/security-checks.yml
    secrets:
      MONDOO_SECRET: ${{ secrets.MONDOO_SECRET }}
